security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Konkurencia Admin"

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_SUPERADMIN] }

    providers:
        in_memory:
            memory:
                users:
                    admin:  { password: changemypwpls, roles: ['ROLE_ADMIN', 'ROLE_SUPERADMIN'] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext