parameters:
#    konkurencia_common.example.class: Konkurencia\CommonBundle\Example

services:


#form services
    krc.type.admin_image:
        class: Teo\MontessoriBundle\Form\Type\KrcAdminImageType
        tags:
            - { name: form.type, alias: krc_admin_image }
